core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('empresarios/', include('empresarios.urls')),
    path('investidores/', include('investidores.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investidores/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sugestao/', views.sugestao, name="sugestao"),
    path('ver_empresa/<int:id>', views.ver_empresa, name="ver_empresa"),
    path('realizar_proposta/<int:id>', views.realizar_proposta, name="realizar_proposta"),
    path('assinar_contrato/<int:id>', views.assinar_contrato, name="assinar_contrato"),
]

empresarios/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.utils.safestring import mark_safe

class Empresas(models.Model):
    tempo_existencia_choices = (
        ('-6', 'Menos de 6 meses'),
        ('+6', 'Mais de 6 meses'),
        ('+1', 'Mais de 1 ano'),
        ('+5', 'Mais de 5 anos')
        
    )
    estagio_choices = (
        ('I', 'Tenho apenas uma idea'),
        ('MVP', 'Possuo um MVP'),
        ('MVPP', 'Possuo um MVP com clientes pagantes'),
        ('E', 'Empresa pronta para escalar'),
    )
    area_choices = (
        ('ED', 'Ed-tech'),
        ('FT', 'Fintech'),
        ('AT', 'Agrotech'),
        
    )
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=50)
    cnpj = models.CharField(max_length=30)
    site = models.URLField()
    tempo_existencia = models.CharField(max_length=2, choices=tempo_existencia_choices, default='-6')
    descricao = models.TextField() 
    data_final_captacao = models.DateField()
    percentual_equity = models.IntegerField() # Percentual esperado
    estagio = models.CharField(max_length=4, choices=estagio_choices, default='I')
    area = models.CharField(max_length=3, choices=area_choices)
    publico_alvo = models.CharField(max_length=3)
    valor = models.DecimalField(max_digits=9, decimal_places=2) # Valor total a ser vendido
    pitch = models.FileField(upload_to='pitchs')
    logo = models.FileField(upload_to='logo')

    def __str__(self):
        return f'{self.user.username} | {self.nome}'
    
    @property
    def status(self):
        if date.today() > self.data_final_captacao:
            return mark_safe('<span class="badge bg-success">Captação finalizada</span>')
        return mark_safe('<span class="badge bg-primary">Em captação</span>')
    @property
    def valuation(self):
        return float(f'{(100 * self.valor) / self.percentual_equity:.2f}')
    
class Documento(models.Model):
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    arquivo = models.FileField(upload_to="documentos")

    def __str__(self):
        return self.titulo
    
class Metricas(models.Model):
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    valor = models.FloatField()

    def __str__(self):
        return self.titulo

investidores/models.py
from django.db import models
from empresarios.models import Empresas
from django.contrib.auth.models import User

class PropostaInvestimento(models.Model):
    status_choices = (
        ('AS', 'Aguardando assinatura'),
        ('PE', 'Proposta enviada'),
        ('PA', 'Proposta aceita'),
        ('PR', 'Proposta recusada')
    )
    valor = models.DecimalField(max_digits=9, decimal_places=2)
    percentual = models.FloatField()
    empresa = models.ForeignKey(Empresas, on_delete=models.DO_NOTHING)
    investidor = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=2, choices=status_choices, default='AS')
    selfie = models.FileField(upload_to="selfie", null=True, blank=True)
    rg = models.FileField(upload_to="rg", null=True, blank=True)

    def __str__(self):
        return str(self.valor)
    
    @property
    def valuation(self):
        return (100 * float(self.valor)) / float(self.percentual)

investidores/views.py
from django.shortcuts import render, redirect
from empresarios.models import Empresas, Documento
from .models import PropostaInvestimento
from django.http import HttpResponse, Http404
from django.contrib.messages import constants
from django.contrib import messages


def sugestao(request):
    areas = Empresas.area_choices
    if request.method == 'GET':
        return render(request, 'sugestao.html', {'areas':areas})
    elif request.method == 'POST':
        tipo = request.POST.get('tipo')
        area = request.POST.getlist('area')
        valor = request.POST.get('valor')

        if tipo == 'C':
            empresas = Empresas.objects.filter(tempo_existencia='+5').filter(estagio='E')
        elif tipo == 'D':
            empresas = Empresas.objects.filter(tempo_existencia__in=['-6', '+6', '+1']).exclude(estagio='E')

        empresas = empresas.filter(area__in=area)
        print(empresas)
        empresas_selecionadas = []
        for empresa in empresas:
            percentual = float(valor) * 100 / float(empresa.valuation)
            if percentual >= 1:
                empresas_selecionadas.append(empresa)

        return render(request, 'sugestao.html', {'areas':areas, 'empresas':empresas_selecionadas})
    
def ver_empresa(request, id):
    empresa = Empresas.objects.get(id=id)
    documentos = Documento.objects.filter(empresa=empresa) 

    proposta_investimanto = PropostaInvestimento.objects.filter(empresa=empresa).filter(status='PA')
    percentual_vendido = 0
    for pi in proposta_investimanto:
        percentual_vendido = percentual_vendido + pi.percentual

    limiar = (80 * empresa.percentual_equity)  / 100
    concretizado = False
    if percentual_vendido >= limiar:
        concretizado = True

    percentual_disponivel = empresa.percentual_equity - percentual_vendido
    return render (request, 'ver_empresa.html', {'empresa':empresa, 'documentos':documentos, 'percentual_vendido':int(percentual_vendido), 
                                                 'concretizado':concretizado, 'percentual_disponivel':percentual_disponivel})

def realizar_proposta(request, id):
    valor = request.POST.get('valor')
    percentual = request.POST.get('percentual')
    empresa = Empresas.objects.get(id=id)

    propostas_aceitas = PropostaInvestimento.objects.filter(empresa=empresa).filter(status='PA')
    
    total = 0
    for pa in propostas_aceitas:
        total = total + pa.percentual
    if total + float(percentual) > empresa.percentual_equity:
        messages.add_message(request, constants.WARNING, 'O percentual solicitado ultrapassa o percentual maximo')
        return redirect (f'/investidores/ver_empresa/{id}')

    valuation = (100 * int(valor)) / int(percentual)

    if valuation < (int(empresa.valuation/2)):
        messages.add_message(request, constants.WARNING, f'O seu valuantion proprosto foi R${valuation} e deve ser no minimo {empresa.valuation}')
        return redirect (f'/investidores/ver_empresa/{id}')

    pi = PropostaInvestimento(
        valor=valor,
        percentual=percentual,
        empresa=empresa,
        investidor=request.user
    )
    pi.save()

    return redirect(f'/investidores/assinar_contrato/{pi.id}')

def assinar_contrato(request, id):
    pi = PropostaInvestimento.objects.get(id=id)

    if pi.status != 'AS':
        raise Http404()
    
    if request.method == 'GET':
        return render(request, 'assinar_contrato.html', {'pi':pi})
    
    elif request.method == 'POST':
        selfie = request.FILES.get('selfie')
        rg = request.FILES.get('rg')

        pi.selfie = selfie
        pi.rg = rg
        pi.status = 'PE'

        pi.save()

        messages.add_message(request, constants.SUCCESS, f'Contrato assinado com sucesso, sua proposta foi enviada a empresa.')
        return redirect(f'/investidores/ver_empresa/{pi.empresa.id}')

        return HttpResponse(id)

investidores/templates/assinar_contrato.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'empresarios/css/listar_empresas.css' %}">
<link rel="stylesheet" href="{% static 'empresarios/css/empresa.css' %}">
<link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">

{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/barra_navegacao.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
            
                            </section>
                        {% endfor %}
                    {% endif %}
                    <div class="col-md-3">
                        <img src="{{pi.empresa.logo.url}}" class="foto-empresa" alt="">
                    </div>
                    <div class="col-md">
                        <h3>Assinar contrato</h3>
                    </div>
                    
                </div>    
        </div>
        <div style="margin-top: 40px; padding: 20px" class="contrato dark-color">
            <h3>Contrato de investimento</h3>
            <p>Ao assinar esse contrato você concorda com todas as cláusulas abaixo</p>
            
            <ol>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
            </ol>

        </div>
        <form action="{% url 'assinar_contrato' pi.id %}" enctype='multipart/form-data' method="POST" style="margin-top: 20px;"> {% csrf_token %}
            <input type="file" name="selfie" class="form-control" style="width: 40%">
            <br>
            <input type="file" name="rg" class="form-control" style="width: 40%">
            <br>
            <input type="submit" class="btn btn-indigo-normal" value="Assinar contrato">
        </form>
    </div>
    <br><br>
{% endblock 'body' %}

investidores/templates/sugestao.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

<link rel="stylesheet" href="{% static 'empresarios/css/listar_empresas.css' %}">
<link rel="stylesheet" href="{% static 'empresarios/css/empresa.css' %}">
<link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
<link rel="stylesheet" href="{% static 'investidores/css/investidores.css' %}">

{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/barra_navegacao.html" %}
    <br><br>
    <div class="container">
        <div class="centralizar">
            <h2>Receba sugestões de empresas</h2>
            <p>Vamos analisar seu perfil e indicar as melhores opções de investimentos</p>
        </div>
        <br>
        <div class="dark-color cont-sugestao">
            <h3>Tipo de investidor</h3>
            <div style="width: 60%">
                <form action="{% url 'sugestao' %}" method="POST">{% csrf_token %}
                    <p>Selecione conservador caso busque investimentos de menos risco
                        e com menor retorno, selecione despojado se prefere correr mais riscos
                        e ter maiores possíbilidades de retorno.</p>
                    <select name="tipo" id="" class="form-select">
                        <option value="C">Conservador</option>
                        <option value="D">Despojado</option>
                    </select>
                    <br>
                    <h3>Áreas de interesses</h3>
                    <p>Selecione as áreas de mercado que possui interesse em investir</p>
                    <select name="area" id="" class="form-select" multiple>
                        {% for area in areas %}
                            <option value="{{area.0}}">{{area.1}}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <h3>Valor que deseja investir</h3>
                    <p>Coloque o valor máximo que deseja investir</p>
                    <input type="number" name="valor" class="form-control" placeholder="00,00">
                    <br>
                    <input type="submit" class="btn btn-indigo">
                </form>
            </div>
            
        </div>

        <br>
        <br>

        <div class="row">
            {% for empresa in empresas %}
                <div class="col-md">
                    <div class="card dark-color" style="width: 18rem; border: none;" >
                        <img class="card-img-top dark-color" src="{{empresa.logo.url}}" alt="Card image cap">
                        <div class="card-body dark-color">
                        <h5 class="card-title">{{empresa.nome}}</h5>
                        <p class="card-text">{{empresa.descricao}}</p>
                        <a href="{% url 'ver_empresa' empresa.id %}" class="btn btn-indigo">Acessar</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock 'body' %}

investidores/templates/ver_empresa.html
{% extends "base.html" %}
{% load static %}
{% block 'head' %}

	<link rel="stylesheet" href="{% static 'empresarios/css/listar_empresas.css' %}">
	<link rel="stylesheet" href="{% static 'empresarios/css/empresa.css' %}">
	<link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
	
{% endblock 'head' %}


{% block 'body' %}
    {% include "partials/barra_navegacao.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    {% if messages %}
                        {% for message in messages %}
                            <section class="alert {{message.tags}}">
                                {{message}}
            
                            </section>
                        {% endfor %}
                    {% endif %}
                    <div class="col-md-3">
                        <img src="{{empresa.logo.url}}" class="foto-empresa" alt="">
                    </div>
                    <div class="col-md">
                        <h3>{{empresa.nome}}</h3>
                        <span class="badge bg-primary">{{empresa.get_area_display}}</span>
                    </div>
                    
                </div>
                <br><br>
                <div class="progress" wtyle="80%">
                    <div class="progress-bar bg-success"
                         style="width:{{percentual_vendido}}%"></div>
                </div>
                <br>
                    {% if concretizado %}
                    <span class="badge bg-success">V</span><span>&nbsp &nbsp A empresa já atingiu 80% do percentual captado, portanto seu investimento será concretizado.</span>
                    {% else %}
                   <span class="badge bg-warning">x</span><span>&nbsp &nbsp Seu investimento será concretizado caso a empresa atinja pelo meno 80% do valor esperado até a data final.</span>
                    {% endif %}
                <hr>
                <p>{{empresa.descricao}}</p>
                <div class="col-md">
                    <h5>Valuation esperado</h5>
                    <span class="sub-fonte">Esperado: {{empresa.valuation}}</span>
                    <br>
                    <br>
                    <h5>Percentual</h5>
                    <span class="sub-fonte">Total a venda: {{empresa.percentual_equity}}%</span>
                    <br>
                    <span class="sub-fonte">Disponivel à compra: {{percentual_disponivel}}%</span>
                </div>
                <br>
                <span class="badge bg-warning">{{empresa.publico_alvo}}</span>
                <br><br>
                <h4 style="color: #92D5EB">Indicadores |</h4>
                
                <div class="row">
                    <div class="col-md-3" >
                        <div class="dark-color" style="padding: 20px; text-align: center;">
                            <h5>CAC</h5>
                            <h6>R$ 200</h6>
                        </div>
                    </div>
                    <div class="col-md-3" >
                        <div class="dark-color" style="padding: 20px; text-align: center;">
                            <h5>CAC</h5>
                            <h6>R$ 200</h6>
                        </div>
                    </div>
                    
                  
                </div>

                <hr>
                <div class="row">
                    <h4>Faça sua proposta</h4>
                    <br><br>
                    <div class="col-md">
                        <form action="{% url 'realizar_proposta' empresa.id%}" method="POST"> {% csrf_token %}
                            <input type="number" name="valor" class="form-control" placeholder="Valor para investir">
                            <br>
                            <input type="submit" class="btn btn-indigo-normal" value="Salvar">
                    </div>
                    <div class="col-md">
                            <input type="number" name="percentual" class="form-control" placeholder="Percentual desejado">
                        </form>
                    </div>
                    
                </div>
            </div>
            <div class="col-md-5 intereses-investimentos">
                <video name='demo' controls autoplay width='100%'>
                    <source src="{{empresa.pitch.url}}" type="video/mp4"></source>
                </video>

                <hr>
                    {% for doc in documentos %}
                    <div class="list_documentos">
                        <div class="row">
                            <div class="col-md-2" style="text-align: center">
                                <a href="{{doc.arquivo.url}}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" style="color: white;" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                                        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
                                        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                                    </svg>
                                </a>
                                
                            </div>
                            <div class="col-md-6">{{doc.titulo}}</div>
                            <div class="col-md-4" style="text-align: right;">
                                
                            </div>
                        </div>
                    </div>
                    {% endfor %}
            </div>
        </div>
    </div>
    <br><br>
{% endblock 'body' %}